/**
 * Generate Go Testcontainers (testcontainers-go) bootstrap code.
 *
 * Per the issue specification, the Go target uses `GenericContainer` uniformly
 * for every service (rather than first-class modules). This keeps the emitted
 * code on testcontainers-go's most stable API surface, which has not changed
 * across releases — first-class module constructors have. The connection
 * string is assembled from `Host()` + `MappedPort()`.
 *
 * Containers are started once in `TestMain` and shared across the whole test
 * suite (Testcontainers best practice: shared-per-suite, not per-test), and
 * are started in dependency (`depends_on`) order.
 */

import { topoSort, type ServiceDef } from "../services.js";

export interface GoGenOptions {
  /** Go package name for the generated file. */
  packageName?: string;
}

/** Generate a single `*_test.go` source file for all services. */
export function generateGo(
  services: ServiceDef[],
  options: GoGenOptions = {},
): string {
  const pkg = sanitizePackage(options.packageName ?? "testsuite");
  const ordered = topoSort(services);

  if (ordered.length === 0) {
    return `package ${pkg}\n\n// No services were declared in the devcontainer; nothing to generate.\n`;
  }

  const ident = uniqueIdents(ordered);

  const lines: string[] = [];
  lines.push("// Code generated by `daax dev generate-tests`. DO NOT EDIT.");
  lines.push("// Regenerate after changing the devcontainer service definitions.");
  lines.push("");
  lines.push(`package ${pkg}`);
  lines.push("");
  lines.push("import (");
  lines.push('\t"context"');
  lines.push('\t"fmt"');
  lines.push('\t"log"');
  lines.push('\t"os"');
  lines.push('\t"testing"');
  lines.push("");
  lines.push('\t"github.com/testcontainers/testcontainers-go"');
  lines.push('\t"github.com/testcontainers/testcontainers-go/wait"');
  lines.push(")");
  lines.push("");

  // Shared, suite-scoped connection strings.
  lines.push("// Connection strings shared across the whole test suite. They are");
  lines.push("// populated once in TestMain and remain valid for every test.");
  lines.push("var (");
  for (const svc of ordered) {
    lines.push(`\t${ident.get(svc.name)}ConnString string`);
  }
  lines.push(")");
  lines.push("");

  // TestMain: start all containers in dependency order, run, then terminate.
  lines.push("// TestMain starts every backing service exactly once for the suite,");
  lines.push("// in dependency order, and tears them down afterwards.");
  lines.push("func TestMain(m *testing.M) {");
  lines.push("\tctx := context.Background()");
  lines.push("\tvar terminators []func()");
  lines.push("\tcleanup := func() {");
  lines.push("\t\tfor i := len(terminators) - 1; i >= 0; i-- {");
  lines.push("\t\t\tterminators[i]()");
  lines.push("\t\t}");
  lines.push("\t}");
  lines.push("");

  for (const svc of ordered) {
    lines.push(...startBlock(svc, ident.get(svc.name)!));
    lines.push("");
  }

  lines.push("\tcode := m.Run()");
  lines.push("\tcleanup()");
  lines.push("\tos.Exit(code)");
  lines.push("}");
  lines.push("");

  // A connectivity smoke test per service.
  for (const svc of ordered) {
    const id = ident.get(svc.name)!;
    const fn = capitalize(id);
    lines.push(`// Test${fn}Connection verifies the ${svc.name} container started`);
    lines.push("// and exposed a usable connection string.");
    lines.push(`func Test${fn}Connection(t *testing.T) {`);
    lines.push(`\tif ${id}ConnString == "" {`);
    lines.push(`\t\tt.Fatal("${svc.name} connection string was not initialized")`);
    lines.push("\t}");
    lines.push(`\tt.Logf("${svc.name} available at %s", ${id}ConnString)`);
    lines.push("}");
    lines.push("");
  }

  return lines.join("\n");
}

/** Emit the container start + connection-string assembly for one service. */
function startBlock(svc: ServiceDef, id: string): string[] {
  const portSpec = `${svc.port}/tcp`;
  const l: string[] = [];
  l.push(`\t// ---- ${svc.name} (${svc.image}) ----`);
  l.push(`\t${id}Req := testcontainers.ContainerRequest{`);
  l.push(`\t\tImage:        ${q(svc.image)},`);
  l.push(`\t\tExposedPorts: []string{${q(portSpec)}},`);
  const envEntries = Object.entries(svc.env);
  if (envEntries.length > 0) {
    l.push("\t\tEnv: map[string]string{");
    for (const [k, v] of envEntries) {
      l.push(`\t\t\t${q(k)}: ${q(v)},`);
    }
    l.push("\t\t},");
  }
  l.push(`\t\tWaitingFor:   wait.ForListeningPort(${q(portSpec)}),`);
  l.push("\t}");
  l.push(`\t${id}C, err := testcontainers.GenericContainer(ctx, testcontainers.GenericContainerRequest{`);
  l.push(`\t\tContainerRequest: ${id}Req,`);
  l.push("\t\tStarted:          true,");
  l.push("\t})");
  l.push("\tif err != nil {");
  l.push("\t\tcleanup()");
  l.push(`\t\tlog.Fatalf("start ${svc.name}: %s", err)`);
  l.push("\t}");
  l.push("\tterminators = append(terminators, func() {");
  l.push(`\t\tif err := ${id}C.Terminate(ctx); err != nil {`);
  l.push(`\t\t\tlog.Printf("terminate ${svc.name}: %s", err)`);
  l.push("\t\t}");
  l.push("\t})");
  l.push(`\t${id}Host, err := ${id}C.Host(ctx)`);
  l.push("\tif err != nil {");
  l.push("\t\tcleanup()");
  l.push(`\t\tlog.Fatalf("${svc.name} host: %s", err)`);
  l.push("\t}");
  l.push(`\t${id}Port, err := ${id}C.MappedPort(ctx, ${q(portSpec)})`);
  l.push("\tif err != nil {");
  l.push("\t\tcleanup()");
  l.push(`\t\tlog.Fatalf("${svc.name} port: %s", err)`);
  l.push("\t}");
  l.push(`\t${id}ConnString = ${connString(svc, id)}`);
  return l;
}

/** Build the Go expression that assembles a connection string for a service. */
function connString(svc: ServiceDef, id: string): string {
  const host = `${id}Host`;
  const port = `${id}Port.Port()`;
  switch (svc.kind) {
    case "postgres": {
      // Credentials are passed as %s args (never interpolated into the format
      // string) so a value containing % or " cannot corrupt fmt or the literal.
      // They are also URL-encoded at generation time so URL-significant
      // characters (@ / ? #) don't break clients parsing the DSN.
      const user = svc.env.POSTGRES_USER || "postgres";
      const pass = svc.env.POSTGRES_PASSWORD || "postgres";
      const db = svc.env.POSTGRES_DB || user;
      const enc = (v: string) => q(encodeURIComponent(v));
      return `fmt.Sprintf("postgres://%s:%s@%s:%s/%s?sslmode=disable", ${enc(user)}, ${enc(pass)}, ${host}, ${port}, ${enc(db)})`;
    }
    case "mysql": {
      const user = svc.env.MYSQL_USER || "root";
      const pass = svc.env.MYSQL_PASSWORD || svc.env.MYSQL_ROOT_PASSWORD || "";
      const db = svc.env.MYSQL_DATABASE || "";
      return `fmt.Sprintf("%s:%s@tcp(%s:%s)/%s", ${q(user)}, ${q(pass)}, ${host}, ${port}, ${q(db)})`;
    }
    case "redis":
      return `fmt.Sprintf("redis://%s:%s", ${host}, ${port})`;
    case "mongodb":
      return `fmt.Sprintf("mongodb://%s:%s", ${host}, ${port})`;
    case "elasticsearch":
      return `fmt.Sprintf("http://%s:%s", ${host}, ${port})`;
    default:
      return `fmt.Sprintf("%s:%s", ${host}, ${port})`;
  }
}

/** Quote a Go string literal. */
function q(s: string): string {
  return JSON.stringify(s);
}

function capitalize(s: string): string {
  return s.length === 0 ? s : s[0].toUpperCase() + s.slice(1);
}

/** Convert a service name into a lower-camelCase Go identifier. */
function goIdent(name: string): string {
  const parts = name
    .replace(/[^a-zA-Z0-9]+/g, " ")
    .trim()
    .split(/\s+/)
    .filter(Boolean);
  if (parts.length === 0) return "svc";
  let out = parts
    .map((p, i) => (i === 0 ? p.toLowerCase() : capitalize(p)))
    .join("");
  if (/^[0-9]/.test(out)) out = "s" + out;
  return out;
}

/** Build a map of service name -> unique Go identifier. */
function uniqueIdents(services: ServiceDef[]): Map<string, string> {
  const map = new Map<string, string>();
  const used = new Set<string>();
  for (const svc of services) {
    let id = goIdent(svc.name);
    let n = 2;
    while (used.has(id)) id = `${goIdent(svc.name)}${n++}`;
    used.add(id);
    map.set(svc.name, id);
  }
  return map;
}

function sanitizePackage(name: string): string {
  const cleaned = name.replace(/[^a-zA-Z0-9_]/g, "").toLowerCase();
  return cleaned && /^[a-z]/.test(cleaned) ? cleaned : "testsuite";
}
