/**
 * Generate TypeScript/Node Testcontainers bootstrap code.
 *
 * Per the issue specification, the TS target uses first-class Testcontainers
 * modules where one exists (PostgreSqlContainer, RedisContainer,
 * ElasticsearchContainer) and falls back to `GenericContainer` otherwise.
 *
 * Two files are produced:
 *  - `<base>.setup.ts`: a reusable module that starts every service once, in
 *    dependency order, and exposes typed connection strings. Started
 *    containers are torn down via `stop()`.
 *  - `<base>.test.ts`: a sample Vitest suite wiring the setup into
 *    `beforeAll`/`afterAll` so containers are shared across the suite (best
 *    practice: shared-per-suite, not per-test).
 */

import { topoSort, type ServiceDef, type ServiceKindId } from "../services.js";

export interface TsGenOptions {
  /** Base name used for the emitted files and import path. */
  baseName?: string;
}

export interface TsFiles {
  setup: string;
  test: string;
  /** Import specifier (without extension) the test uses for the setup. */
  setupModule: string;
}

const STARTED_TYPE: Record<ServiceKindId, string> = {
  postgres: "StartedPostgreSqlContainer",
  redis: "StartedRedisContainer",
  elasticsearch: "StartedElasticsearchContainer",
  mysql: "StartedTestContainer",
  mongodb: "StartedTestContainer",
  rabbitmq: "StartedTestContainer",
  generic: "StartedTestContainer",
};

export function generateTypeScript(
  services: ServiceDef[],
  options: TsGenOptions = {},
): TsFiles {
  const base = options.baseName ?? "testcontainers";
  const ordered = topoSort(services);
  const ident = uniqueIdents(ordered);

  return {
    setup: renderSetup(ordered, ident),
    test: renderTest(ordered, ident, `./${base}.setup.js`),
    setupModule: `./${base}.setup.js`,
  };
}

function renderSetup(
  ordered: ServiceDef[],
  ident: Map<string, string>,
): string {
  const l: string[] = [];
  l.push("// Code generated by `daax dev generate-tests`. DO NOT EDIT.");
  l.push("// Regenerate after changing the devcontainer service definitions.");
  l.push("");

  if (ordered.length === 0) {
    l.push("// No services were declared in the devcontainer; nothing to generate.");
    l.push("export interface TestServices {");
    l.push("  stop(): Promise<void>;");
    l.push("}");
    l.push("");
    l.push("export async function startTestServices(): Promise<TestServices> {");
    l.push("  return { stop: async () => {} };");
    l.push("}");
    l.push("");
    return l.join("\n");
  }

  l.push(...renderImports(ordered));
  l.push("");

  // Result interface.
  l.push("export interface TestServices {");
  for (const svc of ordered) {
    const id = ident.get(svc.name)!;
    l.push(`  /** ${svc.image} */`);
    l.push(`  ${id}: { container: ${STARTED_TYPE[svc.kind]}; connectionString: string };`);
  }
  l.push("  /** Stop every started container (reverse start order). */");
  l.push("  stop(): Promise<void>;");
  l.push("}");
  l.push("");

  // Startup function.
  l.push("/**");
  l.push(" * Start every backing service once, in dependency order. On any");
  l.push(" * failure, already-started containers are stopped before rethrowing.");
  l.push(" */");
  l.push("export async function startTestServices(): Promise<TestServices> {");
  l.push("  const started: { stop(): Promise<unknown> }[] = [];");
  l.push("  // Stop every container in reverse start order WITHOUT mutating");
  l.push("  // `started`; attempt all stops even if one fails, then rethrow the");
  l.push("  // first error so teardown is complete and idempotent.");
  l.push("  const stop = async (): Promise<void> => {");
  l.push("    let firstError: unknown;");
  l.push("    for (let i = started.length - 1; i >= 0; i--) {");
  l.push("      try {");
  l.push("        await started[i].stop();");
  l.push("      } catch (err) {");
  l.push("        if (firstError === undefined) firstError = err;");
  l.push("      }");
  l.push("    }");
  l.push("    if (firstError !== undefined) throw firstError;");
  l.push("  };");
  l.push("  try {");
  for (const svc of ordered) {
    l.push(...startStatements(svc, ident.get(svc.name)!));
  }
  l.push("    return {");
  for (const svc of ordered) {
    const id = ident.get(svc.name)!;
    l.push(`      ${id}: { container: ${id}Container, connectionString: ${id}ConnString },`);
  }
  l.push("      stop,");
  l.push("    };");
  l.push("  } catch (err) {");
  l.push("    // Preserve the original startup error; if teardown also fails,");
  l.push("    // surface both rather than masking the root cause.");
  l.push("    try {");
  l.push("      await stop();");
  l.push("    } catch (teardownErr) {");
  l.push("      throw new AggregateError(");
  l.push("        [err, teardownErr],");
  l.push('        "startup failed and cleanup of started containers also failed",');
  l.push("      );");
  l.push("    }");
  l.push("    throw err;");
  l.push("  }");
  l.push("}");
  l.push("");
  return l.join("\n");
}

/** Statements that start one service and compute its connection string. */
function startStatements(svc: ServiceDef, id: string): string[] {
  const l: string[] = [];
  l.push(`    // ${svc.name} (${svc.image})`);
  // Each branch builds a `new <Container>(image)<...config>.start()` chain so
  // the devcontainer's declared configuration (credentials, env) is preserved.
  const chain = builderChain(svc);
  l.push(`    const ${id}Container = await ${chain};`);
  l.push("    started.push(" + id + "Container);");
  switch (svc.kind) {
    case "postgres":
      l.push(`    const ${id}ConnString = ${id}Container.getConnectionUri();`);
      break;
    case "redis":
      l.push(`    const ${id}ConnString = ${id}Container.getConnectionUrl();`);
      break;
    case "elasticsearch":
      l.push(`    const ${id}ConnString = ${id}Container.getHttpUrl();`);
      break;
    default:
      l.push(`    const ${id}ConnString = \`\${${id}Container.getHost()}:\${${id}Container.getMappedPort(${svc.port})}\`;`);
  }
  return l;
}

/**
 * Render the `new <Container>(image)<config>.start()` expression for a service,
 * mapping declared compose env onto the module's first-class setters (so
 * `getConnectionUri()` reflects the real credentials) or `withEnvironment`.
 */
function builderChain(svc: ServiceDef): string {
  const img = q(svc.image);
  const parts: string[] = [];
  switch (svc.kind) {
    case "postgres": {
      parts.push(`new PostgreSqlContainer(${img})`);
      if (svc.env.POSTGRES_USER) parts.push(`.withUsername(${q(svc.env.POSTGRES_USER)})`);
      if (svc.env.POSTGRES_PASSWORD) parts.push(`.withPassword(${q(svc.env.POSTGRES_PASSWORD)})`);
      if (svc.env.POSTGRES_DB) parts.push(`.withDatabase(${q(svc.env.POSTGRES_DB)})`);
      // Forward any remaining env (e.g. POSTGRES_INITDB_ARGS, PGDATA).
      addExtraEnv(parts, svc.env, ["POSTGRES_USER", "POSTGRES_PASSWORD", "POSTGRES_DB"]);
      break;
    }
    case "redis":
      parts.push(`new RedisContainer(${img})`);
      if (svc.env.REDIS_PASSWORD) parts.push(`.withPassword(${q(svc.env.REDIS_PASSWORD)})`);
      addExtraEnv(parts, svc.env, ["REDIS_PASSWORD"]);
      break;
    case "elasticsearch":
      parts.push(`new ElasticsearchContainer(${img})`);
      if (Object.keys(svc.env).length > 0) parts.push(`.withEnvironment(${envObject(svc.env)})`);
      break;
    default:
      parts.push(`new GenericContainer(${img})`);
      parts.push(`.withExposedPorts(${svc.port})`);
      if (Object.keys(svc.env).length > 0) parts.push(`.withEnvironment(${envObject(svc.env)})`);
  }
  parts.push(".start()");
  return parts.join("");
}

/** Append `.withEnvironment({...})` for env keys not consumed by typed setters. */
function addExtraEnv(
  parts: string[],
  env: Record<string, string>,
  consumed: string[],
): void {
  const extra = Object.fromEntries(
    Object.entries(env).filter(([k]) => !consumed.includes(k)),
  );
  if (Object.keys(extra).length > 0) {
    parts.push(`.withEnvironment(${envObject(extra)})`);
  }
}

function envObject(env: Record<string, string>): string {
  const obj = Object.entries(env)
    .map(([k, v]) => `${q(k)}: ${q(v)}`)
    .join(", ");
  return `{ ${obj} }`;
}

function renderImports(ordered: ServiceDef[]): string[] {
  const kinds = new Set(ordered.map((s) => s.kind));
  const imports: string[] = [];
  if (kinds.has("postgres")) {
    imports.push(
      'import { PostgreSqlContainer, StartedPostgreSqlContainer } from "@testcontainers/postgresql";',
    );
  }
  if (kinds.has("redis")) {
    imports.push(
      'import { RedisContainer, StartedRedisContainer } from "@testcontainers/redis";',
    );
  }
  if (kinds.has("elasticsearch")) {
    imports.push(
      'import { ElasticsearchContainer, StartedElasticsearchContainer } from "@testcontainers/elasticsearch";',
    );
  }
  // Any kind without a first-class module needs GenericContainer.
  const needsGeneric = ordered.some(
    (s) => !["postgres", "redis", "elasticsearch"].includes(s.kind),
  );
  if (needsGeneric) {
    imports.push(
      'import { GenericContainer, StartedTestContainer } from "testcontainers";',
    );
  }
  return imports;
}

function renderTest(
  ordered: ServiceDef[],
  ident: Map<string, string>,
  setupModule: string,
): string {
  const l: string[] = [];
  l.push("// Code generated by `daax dev generate-tests`. DO NOT EDIT.");
  l.push("// Sample suite demonstrating shared-per-suite container usage.");
  l.push("");
  l.push('import { afterAll, beforeAll, describe, expect, it } from "vitest";');
  l.push(`import { startTestServices, type TestServices } from "${setupModule}";`);
  l.push("");
  l.push('describe("backing services", () => {');
  l.push("  let services: TestServices;");
  l.push("");
  l.push("  // Start containers once for the whole suite, not per test.");
  l.push("  beforeAll(async () => {");
  l.push("    services = await startTestServices();");
  l.push("  }, 120_000);");
  l.push("");
  l.push("  afterAll(async () => {");
  l.push("    await services?.stop();");
  l.push("  });");
  l.push("");
  if (ordered.length === 0) {
    l.push("  it(\"has no services to start\", () => {");
    l.push("    expect(services).toBeDefined();");
    l.push("  });");
  }
  for (const svc of ordered) {
    const id = ident.get(svc.name)!;
    l.push(`  it("starts ${svc.name} and exposes a connection string", () => {`);
    l.push(`    expect(services.${id}.connectionString).toBeTruthy();`);
    l.push("  });");
    l.push("");
  }
  l.push("});");
  l.push("");
  return l.join("\n");
}

function q(s: string): string {
  return JSON.stringify(s);
}

function capitalize(s: string): string {
  return s.length === 0 ? s : s[0].toUpperCase() + s.slice(1);
}

function tsIdent(name: string): string {
  const parts = name
    .replace(/[^a-zA-Z0-9]+/g, " ")
    .trim()
    .split(/\s+/)
    .filter(Boolean);
  if (parts.length === 0) return "svc";
  let out = parts
    .map((p, i) => (i === 0 ? p.toLowerCase() : capitalize(p)))
    .join("");
  if (/^[0-9]/.test(out)) out = "s" + out;
  return out;
}

function uniqueIdents(services: ServiceDef[]): Map<string, string> {
  const map = new Map<string, string>();
  const used = new Set<string>();
  for (const svc of services) {
    let id = tsIdent(svc.name);
    let n = 2;
    while (used.has(id)) id = `${tsIdent(svc.name)}${n++}`;
    used.add(id);
    map.set(svc.name, id);
  }
  return map;
}
